// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb21dqknIkHpBfmtNZ5Cg0l4ndakvUqoc',
    appId: '1:407146015368:web:080edad81db59a212f8d3d',
    messagingSenderId: '407146015368',
    projectId: 'sigpen-pruebas',
    authDomain: 'sigpen-pruebas.firebaseapp.com',
    storageBucket: 'sigpen-pruebas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBN-czNT4fGHXsgLHXU4WGc9jSlxKI_xc',
    appId: '1:407146015368:android:e349e5964f20a9af2f8d3d',
    messagingSenderId: '407146015368',
    projectId: 'sigpen-pruebas',
    storageBucket: 'sigpen-pruebas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2P8Nl0JwSHG1ThZX9SK4dLDkp5bolTEI',
    appId: '1:407146015368:ios:a1b5a89f87b3b3a02f8d3d',
    messagingSenderId: '407146015368',
    projectId: 'sigpen-pruebas',
    storageBucket: 'sigpen-pruebas.firebasestorage.app',
    iosBundleId: 'com.example.sigpenCbba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2P8Nl0JwSHG1ThZX9SK4dLDkp5bolTEI',
    appId: '1:407146015368:ios:a1b5a89f87b3b3a02f8d3d',
    messagingSenderId: '407146015368',
    projectId: 'sigpen-pruebas',
    storageBucket: 'sigpen-pruebas.firebasestorage.app',
    iosBundleId: 'com.example.sigpenCbba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb21dqknIkHpBfmtNZ5Cg0l4ndakvUqoc',
    appId: '1:407146015368:web:b0f94a03742eed7c2f8d3d',
    messagingSenderId: '407146015368',
    projectId: 'sigpen-pruebas',
    authDomain: 'sigpen-pruebas.firebaseapp.com',
    storageBucket: 'sigpen-pruebas.firebasestorage.app',
  );

}